[2023-05-31T19:34:57.901+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: extract_dag.extract_task manual__2023-05-31T19:33:44.614201+00:00 [queued]>
[2023-05-31T19:34:57.916+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: extract_dag.extract_task manual__2023-05-31T19:33:44.614201+00:00 [queued]>
[2023-05-31T19:34:57.916+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-31T19:34:57.916+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-05-31T19:34:57.916+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-31T19:34:57.951+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): extract_task> on 2023-05-31 19:33:44.614201+00:00
[2023-05-31T19:34:57.956+0000] {standard_task_runner.py:55} INFO - Started process 40079 to run task
[2023-05-31T19:34:57.963+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'extract_dag', 'extract_task', 'manual__2023-05-31T19:33:44.614201+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/extract_dag.py', '--cfg-path', '/tmp/tmp0sinj30i']
[2023-05-31T19:34:57.965+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask extract_task
[2023-05-31T19:34:58.063+0000] {task_command.py:388} INFO - Running <TaskInstance: extract_dag.extract_task manual__2023-05-31T19:33:44.614201+00:00 [running]> on host codespaces-489347
[2023-05-31T19:34:58.164+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=extract_dag
AIRFLOW_CTX_TASK_ID=extract_task
AIRFLOW_CTX_EXECUTION_DATE=2023-05-31T19:33:44.614201+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-31T19:33:44.614201+00:00
[2023-05-31T19:34:58.165+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-31T19:34:58.166+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'wget -c https://datahub.io/core/top-level-domain-names/r/top-level-domain-names.csv.csv -O /         workspaces/hands-on-introduction-data-engineering-4395021//lab/manual/manual-extract-data.csv']
[2023-05-31T19:34:58.180+0000] {subprocess.py:86} INFO - Output:
[2023-05-31T19:34:58.378+0000] {subprocess.py:93} INFO - /: Is a directory
[2023-05-31T19:34:58.378+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-05-31T19:34:58.393+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-05-31T19:34:58.401+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=extract_dag, task_id=extract_task, execution_date=20230531T193344, start_date=20230531T193457, end_date=20230531T193458
[2023-05-31T19:34:58.450+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 3 for task extract_task (Bash command failed. The command returned a non-zero exit code 1.; 40079)
[2023-05-31T19:34:58.492+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-31T19:34:58.513+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
