[2023-05-31T19:39:05.615+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: extract_dag.extract_task manual__2023-05-31T19:38:59.758546+00:00 [queued]>
[2023-05-31T19:39:05.621+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: extract_dag.extract_task manual__2023-05-31T19:38:59.758546+00:00 [queued]>
[2023-05-31T19:39:05.622+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-31T19:39:05.622+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-05-31T19:39:05.622+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-31T19:39:05.659+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): extract_task> on 2023-05-31 19:38:59.758546+00:00
[2023-05-31T19:39:05.662+0000] {standard_task_runner.py:55} INFO - Started process 42360 to run task
[2023-05-31T19:39:05.666+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'extract_dag', 'extract_task', 'manual__2023-05-31T19:38:59.758546+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/extract_dag.py', '--cfg-path', '/tmp/tmpp5jalq9g']
[2023-05-31T19:39:05.667+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask extract_task
[2023-05-31T19:39:05.773+0000] {task_command.py:388} INFO - Running <TaskInstance: extract_dag.extract_task manual__2023-05-31T19:38:59.758546+00:00 [running]> on host codespaces-489347
[2023-05-31T19:39:05.885+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=extract_dag
AIRFLOW_CTX_TASK_ID=extract_task
AIRFLOW_CTX_EXECUTION_DATE=2023-05-31T19:38:59.758546+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-31T19:38:59.758546+00:00
[2023-05-31T19:39:05.901+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-31T19:39:05.902+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'wget -c https://datahub.io/core/top-level-domain-names/r/top-level-domain-names.csv.csv -O /         workspaces/hands-on-introduction-data-engineering-4395021//lab/manual/manual-extract-data.csv']
[2023-05-31T19:39:05.920+0000] {subprocess.py:86} INFO - Output:
[2023-05-31T19:39:06.026+0000] {subprocess.py:93} INFO - /: Is a directory
[2023-05-31T19:39:06.027+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-05-31T19:39:06.069+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-05-31T19:39:06.073+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=extract_dag, task_id=extract_task, execution_date=20230531T193859, start_date=20230531T193905, end_date=20230531T193906
[2023-05-31T19:39:06.146+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 4 for task extract_task (Bash command failed. The command returned a non-zero exit code 1.; 42360)
[2023-05-31T19:39:06.168+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-31T19:39:06.180+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
